baseurl = "http://blog.gopheracademy.com"
languageCode = "en-us"
title = "Gopher Academy Blog"
disqusShortname = "gopheracademy"
[taxonomies]
   author = "authors"
   series = "series"
   tag = "tags"
   category = "categories"
